#!/usr/bin/env python3
"""
Synthea Data Loader

This script loads synthetic patient data generated by Synthea into the HAPI FHIR server.

Usage:
    python data/load_synthea.py --patients 100 --seed 12345
    
Prerequisites:
    - Synthea installed and in PATH (or specify --synthea-path)
    - HAPI FHIR server running on FHIR_BASE_URL
    - Java 17+ installed
"""

import argparse
import json
import logging
import os
import subprocess
import sys
import requests
from pathlib import Path

from constants import FHIR_BASE_URL

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class SyntheaLoader:
    def __init__(self, fhir_url: str = FHIR_BASE_URL, synthea_path: str = None):
        self.fhir_url = fhir_url.rstrip("/")
        self.synthea_path = synthea_path or "synthea-with-dependencies.jar"
        self.session = requests.Session()
        self.session.headers.update({
            "Accept": "application/fhir+json",
            "Content-Type": "application/fhir+json"
        })

    def generate_patients(self, count: int, seed: int = None, output_dir: str = "output") -> bool:
        """Generate synthetic patients using Synthea"""
        logger.info(f"Generating {count} synthetic patients...")
        
        # Build Synthea command
        cmd = ["java", "-jar", self.synthea_path, "-p", str(count)]
        
        if seed:
            cmd.extend(["-s", str(seed)])
        
        cmd.extend(["-o", output_dir])
        
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=3600)
            
            if result.returncode != 0:
                logger.error(f"Synthea generation failed: {result.stderr}")
                return False
            
            logger.info(f"Successfully generated {count} patients in {output_dir}/fhir")
            return True
            
        except FileNotFoundError:
            logger.error(f"Synthea JAR not found at {self.synthea_path}")
            return False
        except subprocess.TimeoutExpired:
            logger.error("Synthea generation timed out")
            return False
        except Exception as e:
            logger.error(f"Error generating patients: {e}")
            return False

    def load_bundle(self, bundle_path: str) -> bool:
        """Load a FHIR Bundle into the server"""
        try:
            with open(bundle_path, 'r') as f:
                bundle = json.load(f)
            
            # Post bundle to FHIR server
            response = self.session.post(
                self.fhir_url,
                json=bundle,
                timeout=30
            )
            
            if response.status_code in [200, 201]:
                logger.info(f"Successfully loaded {bundle_path}")
                return True
            else:
                logger.error(f"Failed to load bundle: {response.status_code} - {response.text}")
                return False
                
        except Exception as e:
            logger.error(f"Error loading bundle {bundle_path}: {e}")
            return False

    def load_all_bundles(self, output_dir: str = "output") -> int:
        """Load all generated FHIR bundles into the server"""
        fhir_dir = Path(output_dir) / "fhir"
        
        if not fhir_dir.exists():
            logger.error(f"FHIR output directory not found: {fhir_dir}")
            return 0
        
        bundle_files = sorted(fhir_dir.glob("*.json"))
        logger.info(f"Found {len(bundle_files)} bundle files to load")
        
        loaded_count = 0
        for bundle_file in bundle_files:
            if self.load_bundle(str(bundle_file)):
                loaded_count += 1
        
        logger.info(f"Successfully loaded {loaded_count}/{len(bundle_files)} bundles")
        return loaded_count

    def check_server_health(self) -> bool:
        """Check if FHIR server is reachable"""
        try:
            response = self.session.get(
                f"{self.fhir_url}/Patient",
                timeout=5
            )
            if response.status_code in [200, 400]:  # 400 if no results, that's ok
                logger.info(f"FHIR server is healthy")
                return True
            else:
                logger.error(f"FHIR server returned {response.status_code}")
                return False
        except Exception as e:
            logger.error(f"Cannot connect to FHIR server: {e}")
            return False


def main():
    parser = argparse.ArgumentParser(
        description="Generate and load synthetic patient data into HAPI FHIR server"
    )
    parser.add_argument(
        "--patients",
        type=int,
        default=100,
        help="Number of synthetic patients to generate"
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Random seed for reproducible generation"
    )
    parser.add_argument(
        "--synthea-path",
        type=str,
        default="synthea-with-dependencies.jar",
        help="Path to Synthea JAR file"
    )
    parser.add_argument(
        "--fhir-url",
        type=str,
        default=FHIR_BASE_URL,
        help="FHIR server base URL"
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="output",
        help="Directory for Synthea output"
    )
    parser.add_argument(
        "--skip-generation",
        action="store_true",
        help="Skip generation and only load existing bundles"
    )
    
    args = parser.parse_args()
    
    loader = SyntheaLoader(fhir_url=args.fhir_url, synthea_path=args.synthea_path)
    
    # Check server health
    if not loader.check_server_health():
        logger.error("FHIR server is not healthy. Please ensure it's running.")
        sys.exit(1)
    
    # Generate patients if requested
    if not args.skip_generation:
        if not loader.generate_patients(args.patients, args.seed, args.output_dir):
            logger.error("Failed to generate synthetic patients")
            sys.exit(1)
    
    # Load bundles
    loaded = loader.load_all_bundles(args.output_dir)
    
    if loaded == 0:
        logger.error("No bundles were successfully loaded")
        sys.exit(1)
    
    logger.info(f"Data loading complete! Loaded {loaded} patient bundles.")
    sys.exit(0)


if __name__ == "__main__":
    main()
